services:
  - type: web
    name: hr-forms
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hr.wsgi --log-file -"
    healthCheckPath: "/"
    plan: free
    postDeploy:
      - python manage.py migrate
